version: '3.8'

services:
  api:
    build: .
    entrypoint: ./docker-entrypoint.sh
    volumes:
      - .:/usr/src
    restart: always
    ports:
      - "5001-5002:5000"
    environment:
      - FLASK_APP=server.py
      - FLASK_ENV=development
      - FLASK_RUN_HOST=0.0.0.0
    deploy:
      mode: replicated
      replicas: 2       #Change this to change the number of servers
      update_config:
        delay: 1s
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
    networks:
        - app_network
    # workaround for localhost
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    image: nginx:latest
    ports:
      - "5000:5000"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
    - app_network

networks:
  app_network:
