services:
    api:
      build: .
      entrypoint: ./docker-entrypoint.sh
      volumes:
          - .:/usr/src
      networks:
        default: null
      restart: always
      ports:
        - "5000:5000"
      environment:
      - FLASK_APP=server.py
      - FLASK_ENV=development
      - FLASK_RUN_HOST=0.0.0.0

