version: '3.8'

services:
  api:
    build: .
    entrypoint: ./docker-entrypoint.sh
    volumes:
      - .:/usr/src
    restart: always
    ports:
      - "5001-5002:5000"
    environment:
      - FLASK_APP=server.py
      - FLASK_ENV=development
      - FLASK_RUN_HOST=0.0.0.0
    deploy:
      mode: replicated
      replicas: 2
      update_config:
        delay: 1s
      restart_policy:
        condition: any
        delay: 5s
        window: 120s

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro

networks:
  app_network: