services:
    api:
        container_name: rps_server
        build:
            context: .
            dockerfile: Dockerfile
        entrypoint: ./docker-entrypoint.sh
        volumes:
            - .:/usr/src
        networks:
          default: null
        restart: always
        ports:
            - mode: ingress
              target: 5000
              published: "5000"
              protocol: tcp
        depends_on:
          - db

    db:
      container_name: rps_db
      image: postgres:latest
      environment:
          POSTGRES_USER: rps_db_user
          POSTGRES_PASSWORD: rps_db_password
          POSTGRES_DB: rps_gamedata
      networks:
        default: null
      restart: always
      deploy:
        replicas: 1
        restart_policy:
            condition: on-failure

    adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080