services:

  db:
    container_name: rps_db
    image: postgres:latest
    environment:
      POSTGRES_USER: rps_db_user
      POSTGRES_PASSWORD: rps_db_password
      POSTGRES_DB: rps_gamedata
    networks:
      default: null
    restart: always
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - ./data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
