version: '3'
services:
  server:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=server.py
      - FLASK_ENV=development
    volumes:
      - ./server:/app

  client1:
    build: ./client
    stdin_open: true
    tty: true
    depends_on:
      - server

  client2:
    build: ./client
    stdin_open: true
    tty: true
    depends_on:
      - server

